const dict: Dictionary = {
  en: {
    born: "b.",
    death: "Age at death",
    works: "Number of works",
    anniversary: "Upcoming anniversary",
    awareness: "Today's level of awareness",
    abilities: "Musical abilities",
    settings: "Settings",
    browse: "Browse",
    language: "Language",
    categories: "Categories",
    fetching: "Fetching card",
    saveAndClose: "Save and close",
    close: "Close",
    play: "Play",
    npcBegins: "Computer begins",
    npcHas: "Computer has",
    card: "card",
    cardPlural: "s",
    statPlayed: "played",
    draw: "Draw!",
    youWin: "You win :)",
    youLose: "You lose :(",
    continue: "Continue",
    privacy: "Privacy Policy",
    usingYtCookies:
      "We are embedding videos from YouTube, so there will be cookies. You may want to read our ",
    reject: "Reject",
    accept: "Accept",
    goBack: "Back",
    noVideo:
      "Sadly you can not listen to this great piece of music without accepting cookies from YouTube. Here is our ",
    cookieCheckbox: "Accept cookies from YouTube",
    see: "See our",
    welcome: "Welcome",
    chooseCat: "Please choose a category to play",
  },
  de: {
    born: "geb.",
    death: "Lebensjahre",
    works: "Anzahl der Werke",
    anniversary: "Nächstes Jubiläumsjahr",
    awareness: "Bekanntheitsgrad (heute)",
    abilities: "Musikalische Fähigkeiten",
    settings: "Einstellungen",
    browse: "Stöbern",
    language: "Sprache",
    categories: "Kategorien",
    fetching: "Lade Karten",
    saveAndClose: "Speichern und schließen",
    close: "Schließen",
    play: "Spielen",
    npcBegins: "Computer fängt an",
    npcHas: "Computer hat",
    card: "Karte",
    cardPlural: "n",
    statPlayed: "gespielt",
    draw: "Stich!",
    youWin: "Gewonnen :)",
    youLose: "Verloren :(",
    continue: "Weiter",
    privacy: "Datenschutzerklärung",
    usingYtCookies:
      "Wir binden Videos von YouTube ein, d.h. es werden Cookies gesetzt. Details dazu entnehmen Sie bitte unserer ",
    reject: "Bitte nicht",
    accept: "Akzeptieren",
    goBack: "Zurück",
    noVideo:
      "Leider können Sie dieses großartige Werk nicht anhören, ohne Cookies von YouTube zuzulassen. Hier ist unsere ",
    cookieCheckbox: "Cookies von YouTube akzeptieren",
    see: "Siehe unsere",
    welcome: "Willkommen",
    chooseCat: "Bitte wählen Sie eine Kategorie um zu spielen",
  },
}

export { dict }
